export default {
  response_code: 0,
  results: [
    {
      category: "Entertainment: Television",
      type: "multiple",
      difficulty: "easy",
      question: "Who is the star of the AMC series Breaking Bad?",
      correct_answer: "Walter White",
      incorrect_answers: ["Saul Goodman", "Jesse Pinkman", "Skyler White"],
    },
    {
      category: "Animals",
      type: "multiple",
      difficulty: "hard",
      question: "Which species of Brown Bear is not extinct?",
      correct_answer: "Syrian Brown Bear",
      incorrect_answers: [
        "California Grizzly Bear",
        "Atlas Bear",
        "Mexican Grizzly Bear",
      ],
    },
    {
      category: "Entertainment: Video Games",
      type: "boolean",
      difficulty: "easy",
      question:
        "The game &quot;Battlefield 1&quot; takes place during World War I.",
      correct_answer: "True",
      incorrect_answers: ["False"],
    },
    {
      category: "Entertainment: Music",
      type: "multiple",
      difficulty: "medium",
      question: "&quot;Lift Your Spirit&quot; is an album by which artist?",
      correct_answer: "Aloe Blacc",
      incorrect_answers: [
        "Lena Meyer-Landrut",
        "Stevie Wonder",
        "Taylor Swift",
      ],
    },
    {
      category: "Entertainment: Television",
      type: "boolean",
      difficulty: "easy",
      question: "Klingons express emotion in art through opera and poetry.",
      correct_answer: "True",
      incorrect_answers: ["False"],
    },
    {
      category: "General Knowledge",
      type: "multiple",
      difficulty: "medium",
      question: "When did the website &quot;Facebook&quot; launch?",
      correct_answer: "2004",
      incorrect_answers: ["2005", "2003", "2006"],
    },
    {
      category: "History",
      type: "multiple",
      difficulty: "medium",
      question: "How many years did the Hundred Years&#039; War last?",
      correct_answer: "116",
      incorrect_answers: ["100", "90", "101"],
    },
    {
      category: "Entertainment: Music",
      type: "multiple",
      difficulty: "easy",
      question:
        "&quot;Doctor Jones&quot;, &quot;Turn Back Time&quot; and &quot;Barbie Girl&quot; were UK number ones for which Eurodance group?",
      correct_answer: "Aqua",
      incorrect_answers: ["Vengaboys", "Eiffel 65", "Sash!"],
    },
    {
      category: "General Knowledge",
      type: "multiple",
      difficulty: "easy",
      question: "What is Cynophobia the fear of?",
      correct_answer: "Dogs",
      incorrect_answers: ["Birds", "Flying", "Germs"],
    },
    {
      category: "Entertainment: Video Games",
      type: "multiple",
      difficulty: "medium",
      question: "What is a Tetris piece called?",
      correct_answer: "Tetromino",
      incorrect_answers: ["Tetratile", "Tetris", "Tetripiece"],
    },
  ],
};
